name: .NET - CMS - CI/CD

on:
  pull_request:
    types: [ closed ]
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  # CMS Service
  run_if:
    if: contains(github.event.pull_request.labels.*.name, 'cms')
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore Sadin.Cms.sln
    
    - name: Build
      run: dotnet build Sadin.Cms.sln --no-restore
    
    - name: Test
      run: dotnet test Sadin.Cms.sln --no-build --verbosity normal

    - name: Publish 
      run: |
        dotnet publish Sadin.Cms.sln -c Release -o build/cms
    
    - name: Update Connection String
      uses: benday-inc/set-property-value-in-appsettings@main
      with:
        pathToSettingsFile: '${{ github.workspace }}\build\cms\appsettings.json'
        keyname1: 'ConnectionStrings'
        keyname2: 'SqlServerConnection'
        valueToSet: '${{ secrets.CONNECTIONSTRING }}'
        
